project:
  type: book

book:
  title: "QuartoBook"
  author: "Norah Jones"
  date: "13/6/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    include-in-header: 
      - text: |
          \providecommand{\abstractname}{Learning Objectives} % not in scrbook class
          \newenvironment{secabstract}[1]{%
          \hrule
          \small\textbf{\abstractname: } 
          \newline
          \vspace{0.1cm}
          %\small\emph #1     %  emph takes an argument
          \small\emph{#1} % or \small\textit{#1} 
          \itshape % use this if you want the text to be in italics
          }{%
          \hrule
          \vspace{0.6cm}
          }

editor: visual

